create table if not exists public.inquiries (
  id int8 generated by default as identity primary key,
  full_name text not null,
  email text not null,
  whatsapp_number text not null,
  inquiry_type text not null,
  garment_or_service text,
  preferred_sizing text,
  event_or_needed_by text,
  inspiration_references text[] default array[]::text[],
  design_description text not null,
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

drop policy if exists "Allow public inquiry submissions" on public.inquiries;

create policy "Allow public inquiry submissions"
  on public.inquiries
  for insert
  to anon
  with check (true);
